# Generated by Django 3.0.8 on 2020-12-09 17:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201209_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='created_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
